name = "aoc2025"
description = "Advent of Code 2025"
version = "0.1.0-dev"

authors = ["Ethan McDonough"]
maintainers = ["Ethan McDonough <ethanluismcdonough@gmail.com>"]
maintainers-logins = ["ethanluismcdonough"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["aoc2025"]

[[actions]]
type = "pre-build"
command = ["python3", "generate.py"]
